### ISSUE TITLE
Bug when using the release 0.3.3

### ISSUE THREAD

**Issue by marieALaporte** [balhoff/dosdp-tools#16]
I got this error message when running the dosdp-tools command:
Could not find or load main class org.monarchinitiative.dosdp.cli.Main

**Comment by balhoff** [comment]
Hi - a couple of ideas:

Have you kept the `bin` and `lib` folders in the same relative location (to each other)?

Do you have Java 8?

**Comment by marieALaporte** [comment]
That's probably a java version problem because I am running it from the root of the folder.
Chris was able to run it without any trouble. I am thus closing the issue. Thanks for your help
